import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";

export default function Home() {
    const [modal, setModal] = useState(false);
    const [tapCount, setTapCount] = useState(0);

    const [count, setCount] = useState(0);

    const increment = () => setTapCount((prevCount) => prevCount + 1);

    const router = useRouter();

    const createRandomNumber = (min, max) => {
        return Math.floor(Math.random() * (max + 1 - min)) + min;
    };

    const onClick = () => {
        // const increment = tapCount + 1;
        // setTapCount(increment);
        increment();
        if (tapCount % 10 == 0) {
            setModal(true);
        }
        // else {
        //     setModal(false);
        // }
    };
    const test = () => {
        setModal(false);
    };

    useEffect(() => {
        const randomNumber = createRandomNumber(0, 3000);
        setTapCount(randomNumber);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Next Homework</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <button onClick={onClick}>ここを押す</button>
            <div>現在{tapCount}タップ</div>

            {modal && (
                <div className={styles.modalContainer}>
                    <div className={styles.modal}>
                        こんにちは
                        <button
                            onClick={test}
                            // onClick={() => router.reload()}
                        >
                            戻る
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
